const specs = {
  Relationships: [
    "relationship problems",
    "communication difficulties",
    "trust issues",
    "infidelity",
    "jealousy",
    "commitment issues",
    "intimacy issues",
    "financial disagreements",
    "family interference",
    "unresolved conflicts",
    "power struggles",
    "incompatible values",
    "unrealistic expectations",
    "emotional distance",
    "lack of intimacy",
    "grief",
    "emotional distress",
    "study struggles",
    "mental health",
    "coping strategies",
    "moving on",
    "relationship breakup",
    "heartbreak",
    "emotional support",
  ],
  "Family issues": [
    "family conflict",
    "parent-child relationships",
    "communication problems",
    "financial stress",
    "generational differences",
    "grief and loss",
    "addiction",
    "domestic violence",
    "divorce",
    "reconciliation",
    "communication breakdown",
    "parenting strategies",
    "relationship dynamics",
    "legal matters",
    "family relationships",
    "family problems",
    "parenting",
    "family dynamics",
    "communication in family",
    "family counseling",
    "family therapy",
    "family law",
    "child custody",
    "sibling rivalry",
    "divorce",
    "anger",
    "anxiety",
    "parental separation",
    "emotional stress",
    "grief",
    "depression",
    "coping skills",
    "family relationships",
    "therapy",
    "support groups",
  ],
  "Self-esteem": [
    "low confidence",
    "negative thinking",
    "unhappiness",
    "inadequacy",
    "self-doubt",
    "unworthiness",
    "shame",
    "low self-worth",
    "poor self-image",
    "insecurity",
    "pessimism",
    "lack of assertiveness",
    "guilt",
    "inferiority complex",
    "low self-esteem",
    "self-criticism",
    "self-hatred",
    "fear of failure",
    "fear of judgement",
    "feeling of inferiority",
    "feeling inadequate",
    "feeling unloved",
    "feeling worthless",
    "feeling powerless",
    "shyness",
    "feeling ashamed",
    "feeling unlovable",
    "lack of self-respect",
    "bullying",
    "victimization",
    "peer aggression",
    "harassment",
    "cyberbullying",
  ],
  Anxiety: [
    "anxiety",
    "stress",
    "fear",
    "panic",
    "worry",
    "apprehension",
    "nervousness",
    "uneasiness",
    "anxiety disorder",
    "social anxiety",
    "panic attacks",
    "phobias",
    "generalized anxiety",
    "agoraphobia",
    "mental health",
    "obsessive-compulsive disorder",
    "depression",
    "heart palpitations",
    "avoidance",
    "cognitive behavioral therapy",
    "post-traumatic stress disorder",
  ],
  Work: [
    "issues with work",
    "work problems",
    "job stress",
    "work stress",
    "work related stress",
    "work environment",
    "work related issues",
    "work related problem",
    "work related conflict",
    "workplace conflict",
    "work overload",
    "job dissatisfaction",
    "job insecurity",
    "workplace harassment",
    "work life balance",
    "work life conflict",
    "employee morale",
    "absenteeism",
    "job satisfaction",
    "performance management",
    "job security",
    "communication problems",
    "burnout",
    "stress",
    "equity and diversity",
    "performance anxiety",
    "workplace safety",
    "wage disputes",
    "scheduling conflicts",
    "overtime",
    "communication breakdowns",
  ],
  Emotional: [
    "emotional difficulties",
    "mental health",
    "stress",
    "anxiety",
    "depression",
    "grief",
    "self-esteem",
    "trauma",
    "self-harm",
    "burnout",
    "fear",
    "anger",
    "sadness",
    "loneliness",
    "psychological distress",
    "mood disorders",
    "anger management",
    "emotional intelligence",
    "coping skills",
  ],
  Discrimination: [
    "discrimination",
    "prejudice",
    "bigotry",
    "inequality",
    "bias",
    "segregation",
    "intolerance",
    "racism",
    "sexism",
    "ageism",
    "ableism",
    "xenophobia",
    "social inequality",
    "inequity",
    "disparity",
    "stereotypes",
    "gender inequality",
    "exclusion",
    "preference",
    "unfair treatment",
    "preconceived notions",
    "stereotyping",
    "oppression",
    "caste system",
    "unfairness",
    "injustice",
    "bullying",
    "victimization",
    "peer aggression",
    "harassment",
    "cyberbullying",
  ],
  Health: [
    "health",
    "disease",
    "illness",
    "prevention",
    "treatment",
    "symptoms",
    "diagnosis",
    "nutrition",
    "exercise",
    "medication",
    "mental health",
    "cancer",
    "heart disease",
    "diabetes",
    "care",
    "wellness",
    "vaccination",
    "medical conditions",
    "risk factors",
    "substance abuse",
    "disorder",
    "chronic",
    "acute",
    "cardiovascular disease",
    "hypertension",
    "asthma",
    "obesity",
    "arthritis",
    "depression",
    "stroke",
    "kidney disease",
    "infectious disease",
    "alzheimer's disease",
    "hiv",
    "aids",
    "respiratory disease",
    "liver disease",
    "skin disease",
    "osteoporosis",
    "physical health",
    "lifestyle",
    "mental health",
  ],
  Trauma: [
    "psychological trauma",
    "emotional trauma",
    "ptsd",
    "post-traumatic stress disorder",
    "trauma recovery",
    "trauma response",
    "coping mechanisms",
    "traumatic events",
    "mental health",
    "stress",
    "anxiety",
    "depression",
    "psychological impact",
    "mental health care",
    "psychological help",
    "trauma therapy",
    "mental trauma",
    "psychological stress",
    "psychological shock",
    "psychological injury",
    "mental injury",
    "psychological distress",
    "suicidal thoughts",
    "bullying",
    "victimization",
    "peer aggression",
    "harassment",
    "cyberbullying",
    "childhood trauma",
  ],
};
module.exports = specs;
